services:
  core:
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./tools
          target: /app/tools
        - action: rebuild
          path: ./.env

  api:
    command: [
      "uvicorn", "apiDriver:app",
      "--app-dir", "/app/api",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--log-config", "./api/semaphore_api_log_config.json",
      "--reload",
      "--reload-dir", "/app/src",
      "--reload-dir", "/app/api"
    ]
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./tools
          target: /app/tools
        - action: rebuild
          path: ./.env