# Use node image to build and run Vue.js development server
FROM node:14 AS build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json
COPY ./src/Frontend/semaphore-ui/package.json ./package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY ./src/Frontend/semaphore-ui/ ./

#Expose the port
EXPOSE 8080

# Start the Vue.js development server
CMD ["npm", "run", "serve"]
