# -*- coding: utf-8 -*-
#3_6_DatabaseMigration.py
#----------------------------------
# Created By: Anointiyae Beasley
# Created Date: 02/03/2026
# Version 1.0
#----------------------------------
"""This is a database migration script that will initialize version
    3.6 of the database (without using the ORM). It will rename the existing outputs table and create the new outputs table.
"""
#----------------------------------

from DatabaseMigration.IDatabaseMigration import IDatabaseMigration
from sqlalchemy import Engine, text


class Migrator(IDatabaseMigration):

    def update(self, databaseEngine: Engine) -> bool:
        with databaseEngine.connect() as connection:

            # 0) If we already have retired_outputs, we already updated. Bypass.
            retired_exists = connection.execute(text("SELECT to_regclass('public.\"retired_outputs\"');")).scalar()
            if retired_exists is not None:
                connection.commit()
                return True

            # 1) Rename outputs -> retired_outputs
            connection.execute(text('ALTER TABLE public."outputs" RENAME TO "retired_outputs";'))

            # 2) Rename constraints on retired_outputs (exact list from pgAdmin)
            connection.execute(text('ALTER TABLE public."retired_outputs" RENAME CONSTRAINT "outputs_pkey" TO "retired_outputs_pkey";'))
            connection.execute(text('ALTER TABLE public."retired_outputs" RENAME CONSTRAINT "outputs_AK00" TO "retired_outputs_AK00";'))
            connection.execute(text('ALTER TABLE public."retired_outputs" RENAME CONSTRAINT "outputs_dataDatum_fkey" TO "retired_outputs_dataDatum_fkey";'))
            connection.execute(text('ALTER TABLE public."retired_outputs" RENAME CONSTRAINT "outputs_dataLocation_fkey" TO "retired_outputs_dataLocation_fkey";'))
            connection.execute(text('ALTER TABLE public."retired_outputs" RENAME CONSTRAINT "outputs_dataSeries_fkey" TO "retired_outputs_dataSeries_fkey";'))
            connection.execute(text('ALTER TABLE public."retired_outputs" RENAME CONSTRAINT "outputs_dataUnit_fkey" TO "retired_outputs_dataUnit_fkey";'))

            # 3) Rename outputs_id_seq -> retired_outputs_id_seq (if it exists) and reattach
            connection.execute(text("""
            DO $$
            BEGIN
                IF to_regclass('public.outputs_id_seq') IS NOT NULL AND to_regclass('public.retired_outputs_id_seq') IS NULL THEN
                    EXECUTE 'ALTER SEQUENCE public.outputs_id_seq RENAME TO retired_outputs_id_seq';
                END IF;

                IF to_regclass('public.retired_outputs_id_seq') IS NOT NULL THEN
                    EXECUTE 'ALTER TABLE public."retired_outputs" ALTER COLUMN "id" SET DEFAULT nextval(''public.retired_outputs_id_seq'')';
                    EXECUTE 'ALTER SEQUENCE public.retired_outputs_id_seq OWNED BY public."retired_outputs"."id"';
                END IF;
            END $$;
            """))

            # 4) Create NEW outputs table (no ensembleMemberId, dataValue BYTEA)
            connection.execute(text("""
                CREATE TABLE public."outputs" (
                    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
                    "timeGenerated" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                    "leadTime" INTERVAL NOT NULL,
                    "modelName" VARCHAR(50) NOT NULL,
                    "modelVersion" VARCHAR(10) NOT NULL,
                    "dataValue" BYTEA NOT NULL,
                    "dataUnit" VARCHAR(10) NOT NULL,
                    "dataLocation" VARCHAR(25) NOT NULL,
                    "dataSeries" VARCHAR(25) NOT NULL,
                    "dataDatum" VARCHAR(10),

                    CONSTRAINT "outputs_pkey" PRIMARY KEY ("id"),

                    CONSTRAINT "outputs_dataUnit_fkey"
                        FOREIGN KEY ("dataUnit") REFERENCES public."ref_dataUnit" ("code"),

                    CONSTRAINT "outputs_dataLocation_fkey"
                        FOREIGN KEY ("dataLocation") REFERENCES public."ref_dataLocation" ("code"),

                    CONSTRAINT "outputs_dataSeries_fkey"
                        FOREIGN KEY ("dataSeries") REFERENCES public."ref_dataSeries" ("code"),

                    CONSTRAINT "outputs_dataDatum_fkey"
                        FOREIGN KEY ("dataDatum") REFERENCES public."ref_dataDatum" ("code")
                );
            """))

            # 5) Add AK00 exactly like before
            connection.execute(text("""
                ALTER TABLE public."outputs"
                ADD CONSTRAINT "outputs_AK00"
                UNIQUE NULLS NOT DISTINCT ("timeGenerated", "leadTime", "modelName", "modelVersion", "dataLocation", "dataSeries", "dataDatum");
            """))

            connection.commit()
            return True

    def rollback(self, databaseEngine: Engine) -> bool:
        """Rollback behavior:
        - Drop the NEW outputs table
        - Rename retired_outputs back to outputs
        - Restore original constraint + sequence names
        """
        with databaseEngine.connect() as connection:

            # If retired_outputs doesn't exist, nothing to rollback
            retired_exists = connection.execute(text("SELECT to_regclass('public.\"retired_outputs\"');")).scalar()
            if retired_exists is None:
                connection.commit()
                return True

            # 1) Drop the NEW outputs table
            connection.execute(text('DROP TABLE IF EXISTS public."outputs" CASCADE;'))

            # 2) Restore retired_outputs -> outputs
            connection.execute(text('ALTER TABLE public."retired_outputs" RENAME TO "outputs";'))

            # 3) Restore constraint names
            connection.execute(text('ALTER TABLE public."outputs" RENAME CONSTRAINT "retired_outputs_pkey" TO "outputs_pkey";'))
            connection.execute(text('ALTER TABLE public."outputs" RENAME CONSTRAINT "retired_outputs_AK00" TO "outputs_AK00";'))
            connection.execute(text('ALTER TABLE public."outputs" RENAME CONSTRAINT "retired_outputs_dataDatum_fkey" TO "outputs_dataDatum_fkey";'))
            connection.execute(text('ALTER TABLE public."outputs" RENAME CONSTRAINT "retired_outputs_dataLocation_fkey" TO "outputs_dataLocation_fkey";'))
            connection.execute(text('ALTER TABLE public."outputs" RENAME CONSTRAINT "retired_outputs_dataSeries_fkey" TO "outputs_dataSeries_fkey";'))
            connection.execute(text('ALTER TABLE public."outputs" RENAME CONSTRAINT "retired_outputs_dataUnit_fkey" TO "outputs_dataUnit_fkey";'))

            # 4) Restore sequence name outputs_id_seq and reattach (if it exists)
            connection.execute(text("""
            DO $$
            BEGIN
                IF to_regclass('public.retired_outputs_id_seq') IS NOT NULL AND to_regclass('public.outputs_id_seq') IS NULL THEN
                    EXECUTE 'ALTER SEQUENCE public.retired_outputs_id_seq RENAME TO outputs_id_seq';
                END IF;

                IF to_regclass('public.outputs_id_seq') IS NOT NULL THEN
                    EXECUTE 'ALTER TABLE public."outputs" ALTER COLUMN "id" SET DEFAULT nextval(''public.outputs_id_seq'')';
                    EXECUTE 'ALTER SEQUENCE public.outputs_id_seq OWNED BY public."outputs"."id"';
                END IF;
            END $$;
            """))

            connection.commit()
            return True
