# -*- coding: utf-8 -*-
#3_7_DatabaseMigration.py
#----------------------------------
# Created By: Anointiyae Beasley
# Created Date: 03/15/2026
# Version 1.0
#----------------------------------

from DatabaseMigration.IDatabaseMigration import IDatabaseMigration
from sqlalchemy import Engine, text


class Migrator(IDatabaseMigration):

    def update(self, databaseEngine: Engine) -> bool:

        with databaseEngine.connect() as connection:

            # Rename existing inputs table
            connection.execute(text(
                'ALTER TABLE public."inputs" RENAME TO "retired_inputs";'
            ))

            # Rename constraints on retired_inputs
            connection.execute(text("""
                DO $$
                DECLARE
                    r RECORD;
                BEGIN
                    FOR r IN
                        SELECT conname
                        FROM pg_constraint
                        WHERE conrelid = 'public."retired_inputs"'::regclass
                    LOOP
                        IF r.conname NOT LIKE 'retired\\_%' ESCAPE '\\' THEN
                            EXECUTE format(
                                'ALTER TABLE public."retired_inputs" RENAME CONSTRAINT %I TO %I;',
                                r.conname,
                                'retired_' || r.conname
                            );
                        END IF;
                    END LOOP;
                END $$;
            """))

            # Create partitioned inputs table
            connection.execute(text("""
                CREATE TABLE public."inputs" (

                    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,

                    "isActual" BOOLEAN NOT NULL,

                    "generatedTime" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                    "verifiedTime" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                    "acquiredTime" TIMESTAMP WITHOUT TIME ZONE NOT NULL,

                    "latitude" NUMERIC(8,5),
                    "longitude" NUMERIC(8,5),

                    "dataValue" VARCHAR(25) NOT NULL,

                    "dataUnit" VARCHAR(10) NOT NULL,
                    "dataLocation" VARCHAR(25) NOT NULL,
                    "dataSeries" VARCHAR(25) NOT NULL,
                    "dataDatum" VARCHAR(10),
                    "dataSource" VARCHAR(10) NOT NULL,

                    CONSTRAINT "inputs_pkey"
                        PRIMARY KEY ("id"),

                    CONSTRAINT "inputs_AK00"
                        UNIQUE (
                            "isActual",
                            "generatedTime",
                            "verifiedTime",
                            "acquiredTime",
                            "dataUnit",
                            "dataSource",
                            "dataLocation",
                            "dataSeries",
                            "dataDatum",
                            "latitude",
                            "longitude"
                        ),

                    CONSTRAINT "inputs_dataUnit_fkey"
                        FOREIGN KEY ("dataUnit")
                        REFERENCES public."ref_dataUnit" ("code"),

                    CONSTRAINT "inputs_dataLocation_fkey"
                        FOREIGN KEY ("dataLocation")
                        REFERENCES public."ref_dataLocation" ("code"),

                    CONSTRAINT "inputs_dataSeries_fkey"
                        FOREIGN KEY ("dataSeries")
                        REFERENCES public."ref_dataSeries" ("code"),

                    CONSTRAINT "inputs_dataDatum_fkey"
                        FOREIGN KEY ("dataDatum")
                        REFERENCES public."ref_dataDatum" ("code"),

                    CONSTRAINT "inputs_dataSource_fkey"
                        FOREIGN KEY ("dataSource")
                        REFERENCES public."ref_dataSource" ("code")

                )
                PARTITION BY RANGE ("acquiredTime");
            """))

            # Default partition
            connection.execute(text("""
                CREATE TABLE public."inputs_default"
                PARTITION OF public."inputs"
                DEFAULT;
            """))

            # Create partition for current month
            connection.execute(text("""
                DO $$
                DECLARE
                    start_date DATE;
                    end_date DATE;
                    partition_name TEXT;
                BEGIN
                    start_date := date_trunc('month', CURRENT_DATE);
                    end_date := start_date + interval '1 month';

                    partition_name := 'inputs_' || to_char(start_date, 'YYYY_MM');

                    EXECUTE format(
                        'CREATE TABLE IF NOT EXISTS public.%I
                         PARTITION OF public.inputs
                         FOR VALUES FROM (%L) TO (%L)',
                        partition_name,
                        start_date,
                        end_date
                    );
                END $$;
            """))

            # Migrate existing data
            connection.execute(text("""
                INSERT INTO public."inputs"
                SELECT * FROM public."retired_inputs";
            """))

            connection.commit()
            return True


    def rollback(self, databaseEngine: Engine) -> bool:

        with databaseEngine.connect() as connection:

            connection.execute(text(
                'DROP TABLE IF EXISTS public."inputs" CASCADE;'
            ))

            connection.execute(text(
                'ALTER TABLE public."retired_inputs" RENAME TO "inputs";'
            ))

            connection.execute(text("""
                DO $$
                DECLARE
                    r RECORD;
                    new_name TEXT;
                BEGIN
                    FOR r IN
                        SELECT conname
                        FROM pg_constraint
                        WHERE conrelid = 'public."inputs"'::regclass
                        AND conname LIKE 'retired\\_%' ESCAPE '\\'
                    LOOP
                        new_name := substring(r.conname from 9);
                        EXECUTE format(
                            'ALTER TABLE public."inputs" RENAME CONSTRAINT %I TO %I;',
                            r.conname,
                            new_name
                        );
                    END LOOP;
                END $$;
            """))

            connection.commit()
            return True