# -*- coding: utf-8 -*-
#3_7_DatabaseMigration.py
#----------------------------------
# Created By: Anointiyae Beasley
# Created Date: 04/17/2026
# Version 1.0
#----------------------------------
"""This is a database migration script that will initialize version
    3.7 of the database (without using the ORM). It will create a new statistics table.
"""
#----------------------------------

from DatabaseMigration.IDatabaseMigration import IDatabaseMigration
from sqlalchemy import Engine, text


class Migrator(IDatabaseMigration):

    def update(self, databaseEngine: Engine) -> bool:
        """
          Update behavior:
            - Create the new statistics table and it's constraints

        Parameters:
            :param databaseEngine: Engine - the engine of the database we are connecting to (semaphore)
            :return: bool indicating successful update

           

        """
        with databaseEngine.connect() as connection:

            # Create the new statistics table with its constraints
            connection.execute(text("""
                CREATE TABLE public."output_statistics" (
                    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "outputID" INTEGER NOT NULL,

                    "p1" FLOAT NOT NULL,
                    "p5" FLOAT NOT NULL,
                    "p10" FLOAT NOT NULL,
                    "p25" FLOAT NOT NULL,
                    "p50" FLOAT NOT NULL,
                    "p75" FLOAT NOT NULL,
                    "p90" FLOAT NOT NULL,
                    "p95" FLOAT NOT NULL,
                    "p99" FLOAT NOT NULL,

                    "min" FLOAT NOT NULL,
                    "max" FLOAT NOT NULL,
                    "mean" FLOAT NOT NULL,
                    "std_dev" FLOAT NOT NULL,

                    CONSTRAINT "output_statistics_outputID_fkey"
                        FOREIGN KEY ("outputID")
                        REFERENCES public."outputs"("id")
                );
            """))
            # Added an index
            connection.execute(text("""
                CREATE INDEX IF NOT EXISTS idx_output_statistics_outputID
                ON public."output_statistics" ("outputID");
            """))

           
            connection.commit()
            return True

    def rollback(self, databaseEngine: Engine) -> bool:
        """ Rollback behavior:
            - Drop statistics table
        """
        with databaseEngine.connect() as connection:

            # Drop the NEW output_statistics table and it's constraints.
            connection.execute(text("""
                DROP INDEX IF EXISTS public.idx_output_statistics_outputID;
            """))

            connection.execute(text("""
                DROP TABLE IF EXISTS public."output_statistics";
            """))

            connection.commit()
            return True